baseurl = "/"
title = "Core Dump"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Tech blog by Amjith"
  #copyright = "&copy;2016 Your name or company"
  sidebarAbout = ["Tech blog by Amjith123"]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "/"
  home = true

  [[params.navlinks]]
  name = "Personal Blog"
  url = "https://blog.amjith.com"

  [params.social]
  github        = "https://github.com/amjith"
  link          = "https://www.dbcli.com"

